# Generated by Django 5.2 on 2025-04-11 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='slug',
        ),
    ]
