# Generated by Django 5.2 on 2025-04-15 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_remove_song_album_alter_album_created_by_albumsongs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
    ]
